"""Add discount fields to order_items

Revision ID: 92735c1b0068
Revises: ccec7630cc01
Create Date: 2025-11-26 10:58:27.924647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92735c1b0068'
down_revision: Union[str, None] = 'ccec7630cc01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('discount_percentage', sa.Float(), server_default='0', nullable=False))
    op.add_column('order_items', sa.Column('discount_amount', sa.Float(), server_default='0', nullable=False))
    op.create_unique_constraint(None, 'order_items', ['id'])
    op.create_unique_constraint(None, 'orders', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'order_items', type_='unique')
    op.drop_column('order_items', 'discount_amount')
    op.drop_column('order_items', 'discount_percentage')
    # ### end Alembic commands ###
